#!/usr/bin/env bash
# Docwelder local install script (task 14.1).
#
# Usage:  curl -fsSL <stable-url>/install.sh | sh
#
# Uses bash explicitly (not plain /bin/sh) because task 14.1 targets "bash
# and zsh on macOS and Linux" specifically, and bash gives us reliable
# heredocs/arrays for generating the wrapper below. Invoking it via `sh` on
# a system where /bin/sh is bash (macOS) or dash (most Linux) both work
# because the shebang re-execs into bash regardless of how the script is
# invoked (curl | sh simply hands the script text to whatever `sh` is,
# which then honors this file's own shebang once executed as a file — for
# the pipe form we re-exec explicitly below to be safe on dash).
set -euo pipefail

# Re-exec under bash if we were invoked via `sh script.sh` / `... | sh`
# where $0 isn't a real bash process (dash ignores the shebang when read
# from stdin).
if [ -z "${BASH_VERSION:-}" ]; then
  exec bash "$0" "$@"
fi

# ---------------------------------------------------------------------------
# Pinned version. A real release pipeline replaces this line (e.g. via sed)
# with the version being published; defaults to this repo's own VERSION file
# so a local/dev run of this script pins whatever is currently checked out.
# ---------------------------------------------------------------------------
DOCWELDER_PIN_VERSION="${DOCWELDER_PIN_VERSION:-$(cat "$(dirname "$0")/../VERSION" 2>/dev/null || echo "0.1.0")}"
DOCWELDER_IMAGE="ghcr.io/jornr94/docwelder"

log() { printf '%s\n' "$*"; }
fail() {
  printf 'docwelder install: %s\n' "$*" >&2
  exit 1
}

# ---------------------------------------------------------------------------
# 1. Platform check (task 14.3, spec `distribution`: "MVP local shim platform
#    scope" — macOS and Linux only; Windows is refused with a pointer to the
#    `docker run` fallback docs).
# ---------------------------------------------------------------------------
case "${OSTYPE:-$(uname -s)}" in
  msys* | cygwin* | win32* | MINGW* | MSYS*)
    fail "Windows is not supported by this install script in MVP. See docs/windows-fallback.md for the \`docker run\` fallback."
    ;;
esac

UNAME_S="$(uname -s)"
case "$UNAME_S" in
  Darwin | Linux) : ;;
  *)
    fail "Unsupported platform \"$UNAME_S\". Docwelder's install script supports macOS and Linux only in MVP. See docs/windows-fallback.md for the \`docker run\` fallback."
    ;;
esac

# ---------------------------------------------------------------------------
# 2. Container runtime check (task 14.2, 'distribution' spec: "Docker or
#    Podman is a documented prerequisite").
# ---------------------------------------------------------------------------
RUNTIME=""
if command -v docker >/dev/null 2>&1; then
  RUNTIME="docker"
elif command -v podman >/dev/null 2>&1; then
  RUNTIME="podman"
else
  fail "Neither docker nor podman was found on PATH. Install one of them first: https://docs.docker.com/get-docker/ or https://podman.io/docs/installation"
fi

# ---------------------------------------------------------------------------
# 3. Pick an install directory on PATH (task 14.4).
# ---------------------------------------------------------------------------
INSTALL_DIR="$HOME/.local/bin"
mkdir -p "$INSTALL_DIR" 2>/dev/null || true
case ":$PATH:" in
  *":$INSTALL_DIR:"*) : ;;
  *)
    if [ -w "/usr/local/bin" ]; then
      INSTALL_DIR="/usr/local/bin"
    fi
    ;;
esac
mkdir -p "$INSTALL_DIR"

WRAPPER_PATH="$INSTALL_DIR/docwelder"

# ---------------------------------------------------------------------------
# 4. Write the wrapper (tasks 14.5-14.9).
# ---------------------------------------------------------------------------
cat > "$WRAPPER_PATH" <<WRAPPER_EOF
#!/usr/bin/env bash
# Docwelder local wrapper — generated by install.sh. Do not edit by hand;
# re-run the installer or \`docwelder self-update\` instead.
set -euo pipefail

DOCWELDER_RUNTIME="$RUNTIME"
DOCWELDER_IMAGE_REPO="$DOCWELDER_IMAGE"
DOCWELDER_INSTALLED_TAG="$DOCWELDER_PIN_VERSION"
WRAPPER_VERSION="$DOCWELDER_PIN_VERSION"

PIN_FILE="\$HOME/.config/docwelder/pinned-image-tag"
if [ -f "\$PIN_FILE" ]; then
  IMAGE_TAG="\$(cat "\$PIN_FILE")"
else
  IMAGE_TAG="\$DOCWELDER_INSTALLED_TAG"
fi
IMAGE_REF="\$DOCWELDER_IMAGE_REPO:\$IMAGE_TAG"

if [ "\${1:-}" = "--version" ]; then
  echo "docwelder wrapper \$WRAPPER_VERSION (pinned image: \$IMAGE_REF)"
  exit 0
fi

# First-use pull with progress; subsequent runs reuse the local cache
# (task 14.8). The container runtime itself is the cache — \`docker run\`
# only pulls when the tag isn't already present locally.
if [ -z "\$(\$DOCWELDER_RUNTIME images -q "\$IMAGE_REF" 2>/dev/null)" ]; then
  echo "docwelder: pulling \$IMAGE_REF (first use)..." >&2
  "\$DOCWELDER_RUNTIME" pull "\$IMAGE_REF"
fi

# ~/.config/docwelder/ is always mounted (spec: "Wrapper mounts the user
# config directory for every invocation") — this is also how self-update's
# pinned-image-tag override reaches the wrapper. The container's home is
# fixed at /root since the image runs as root (see Dockerfile).
MOUNT_ARGS=(-v "\$HOME/.config/docwelder:/root/.config/docwelder")

# CWD is mounted only for repo-scoped commands (init, upgrade) — never for
# init-user (task: "Wrapper mounts the current working directory for
# repo-scoped commands only").
case "\${1:-}" in
  init | upgrade)
    MOUNT_ARGS+=(-v "\$(pwd):/workspace" -w /workspace)
    ;;
esac

exec "\$DOCWELDER_RUNTIME" run -it --rm \\
  "\${MOUNT_ARGS[@]}" \\
  -e EDITOR="\${EDITOR:-}" \\
  "\$IMAGE_REF" "\$@"
WRAPPER_EOF

chmod +x "$WRAPPER_PATH"

log "docwelder installed to $WRAPPER_PATH (pinned image: $DOCWELDER_IMAGE:$DOCWELDER_PIN_VERSION)"
case ":$PATH:" in
  *":$INSTALL_DIR:"*) : ;;
  *) log "Note: $INSTALL_DIR is not on your PATH yet. Add it to your shell profile, then open a new shell." ;;
esac
